export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export PATH=$PATH:/opt/bin

# CUDA
export PATH=/usr/local/cuda-11.4/bin:$PATH  
export LD_LIBRARY_PATH=/usr/local/cuda-11.4/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda-11.4

# proxy
alias pxy="export ALL_PROXY=http://127.0.0.1:7890"
alias cpxy="unset ALL_PROXY"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_COMPLETION_TRIGGER=']'
